# Generated by Django 5.0.7 on 2024-07-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meublog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
